### ISSUE TITLE
اختلال

### ISSUE THREAD

**Issue by bestkilleriranlod** [Ptechgithub/ReverseTlsTunnel#1]
درود
ممنون از زحمات شما
بطور کامل مراحل انجام شده و اتصال هم برقرار شده
منتها زمانیکه متصل هستم خیلی عالی و سرعت خوبه ولی تقریبا هر ۱۰ الی ۲۰ ثانیه حدودا ۵ ثانیه دیسکانکت میشه و مجدد کانکت میشه
علت میدونید چیه؟

**Comment by Ptechgithub** [comment]
سلام احتمالا مربوط به برنامه هست که باید اپدیت بشه.

**Comment by ramtiny** [comment]
سلام و وقت بخیر
برای منم همین مشکل رو داره
هر چند ثانیه که وصل هشت سرعت عالیه
ولی یهو ۲_۳ ثانیه میزنه connecting
مشکل از چیه بنظرتون
