### ISSUE TITLE
نصب نامیزون

### ISSUE THREAD

**Issue by gorbesiah** [Ptechgithub/ReverseTlsTunnel#10]
سلام روزت بخیر
امیدوارم حالت خوب باشه
با این روش آیا باز هم نیاز به نصب نامیزون روی سرور هست؟

**Comment by Ptechgithub** [comment]
سلام ممنون از شما . این فقط تانله ربطی به نامیزون نداره

**Comment by gorbesiah** [comment]
یعنی الان روی سرور ایران دانلود و آپلودمون مسئله نمیشه؟

**Comment by gorbesiah** [comment]
ممنون از راهنماییتون
در نسخه بعدی آقای radkesvat گفته که Load Balancer اضافه میکنند.
به این نسخه اسکریپت هم اضافه میشه؟

**Comment by Ptechgithub** [comment]
این اسکریپت فقط نصب میکنه هرچی اضافه بشه خودکار با اجرای اسکریپت نصب و اضافه میشه

**Comment by ramtiny** [comment]
این اسکریپت تنظیمات تک پورت هست یا مولتی پورت؟

**Comment by Ptechgithub** [comment]
مولتی پورت

**Comment by ramtiny** [comment]
پس چطور من تک پورت هستم برای من کار می‌کنه

**Comment by Ptechgithub** [comment]
مولتی پورت یعنی اینکه کانفیگهاتون هر پورتی بزارید کار میکنه
