### ISSUE TITLE
باگ

### ISSUE THREAD

**Issue by ojooubeh** [Ptechgithub/ReverseTlsTunnel#11]
درود ، بعد از اجرای اسکریپت تو سرور ایران دیگه نمیشه به سرور ssh زد تا وقتی که سرور نصب مجدد بشه

**Comment by Ptechgithub** [comment]
درود برشما. تست کردم مشکلی نداره روی سرور فقط یک سروریس رو اجرا کنید . یا multiport یا load-balancer

**Comment by SoroushImanian** [comment]
> درود برشما. تست کردم مشکلی نداره روی سرور فقط یک سروریس رو اجرا کنید . یا multiport یا load-balancer

فرق بین load-balancer و multiport چی هست؟ توی این اسکریپت

**Comment by Ptechgithub** [comment]
سرور ایران به جای اینکه تمام دیتای کاربران رو به یه سرور خارج رد و بدل کنه ؛ بیاد دیتای کاربران رو بین چند سرور خارج تقیسم کنه که هم سرعت و کیفیت کانکشن خوب میشه هم تشخیصش سخت تر میشه و اگه یکی از سرور های خارج از دسترس خارج شد  ؛ بغیه سرور ها هستن تا کانکشن رو سرپا نگه دارن.

چند سرور خارج و یک سرور ایران میخواد.

**Comment by SoroushImanian** [comment]
الان من دو سرور خارج و یک ایران دارم load-balancer رو باید استفاده کنم دیگه؟

**Comment by Ptechgithub** [comment]
اجباری نیست ولی اگه داری میتونی استفاده کنی.
