### ISSUE TITLE
مشکل در اتصال به اینترنت مخابرات

### ISSUE THREAD

**Issue by farazalyari** [Ptechgithub/ReverseTlsTunnel#13]
سلام عرض ادب وقتتون بخیر باشه.

بنده همه کارارو انجام میدم همه اپراتورها هم اکیه رو وای فای مخابرات 2020 مشکل دارم اصلا به سختی وصل میشه و اینکه رو vemess هم تست کردم انجام نشد. ممنون میشم راه حل بفرمایید. تشکر.

**Comment by Ptechgithub** [comment]
سلام احتمالا سرورت روی مخابرات مشکل داره با یه سرور دیگه تست کنید

**Comment by farazalyari** [comment]
پیمان جان تو تلگرام برات ویس فرستادم اگر مقدوره جواب بدین ، سرورم روی آی پی
هتزنر آلمانه.
