### ISSUE TITLE
Server iran not install

### ISSUE THREAD

**Issue by siavash3441** [Ptechgithub/ReverseTlsTunnel#14]
install.sh: line 65: unzip: command not found
chmod: cannot access 'RTT': No such file or directory
finished.

Salam server iran in khata ro mide

**Comment by siavash3441** [comment]
install.sh: line 65: unzip: command not found
chmod: cannot access 'RTT': No such file or directory
finished.

سلام سرور ایران این خطا رو میده

**Comment by Ptechgithub** [comment]
اگه سرور ایرانت root نیست اول دستور sudo -i رو بزن تا دسترسی به root بگیری بعد دستور پایین رو بزن تا unzip نصب بشه
sudo apt install unzip
