### ISSUE TITLE
service not start on kharej server

### ISSUE THREAD

**Issue by moslem7026** [Ptechgithub/ReverseTlsTunnel#15]
Which server do you want to use? (Enter '1' for Iran or '2' for Kharej) : 2
Please Enter SNI (default : splus.ir):
Please Enter (IRAN IP) : x.x.x.x
Please Enter Password (Please choose the same password on both servers): P30world
/dev/fd/63: line 54: tunnel.service: Permission denied
Failed to start tunnel.service: Unit tunnel.service not found.
Failed to enable unit: Unit file tunnel.service does not exist.

**Comment by Ptechgithub** [comment]
ببین دسترسی root داری یا نه اگه نه با sudo -i دسترسی روت روفعال کن قبلش یک با روی uninstall بزن بعد install کن . اگه نشد یا سرور رو ریست کن یا روی یه سرور دیگه تست کن
