### ISSUE TITLE
بستن SSH

### ISSUE THREAD

**Issue by farazalyari** [Ptechgithub/ReverseTlsTunnel#16]
سلام عرض ادب بعد اتمام کار لطفا بگین چطور SSH رو ببندیم چون بسته میشه

**Comment by farazalyari** [comment]
سلام عرض ادب بعد اتمام کار لطفا بگین چطور SSH رو ببندیم چون بسته میشه

**Comment by Ptechgithub** [comment]
متوجه نشدم. ssh رو ببندی؟

**Comment by farazalyari** [comment]
عکس دادم تلگرام بزرگوار اونجارم چک کن

**Comment by farazalyari** [comment]
بله چون قطع شدم موقع کار
