### ISSUE TITLE
آیا بعداز ریستارت سرورها دوباره تانل اجرا میشه؟

### ISSUE THREAD

**Issue by abedin70** [Ptechgithub/ReverseTlsTunnel#17]
اسکریپت بعد از ریستارت سرور ها قابلیت اجرا شدن مجدد داره؟ یا باید دوباره دستی اجرا بشه؟

**Comment by Ptechgithub** [comment]
بله از سرویس استفاده شده و با reboot شدن سرور مجدد اجرا میشه
