### ISSUE TITLE
نصب بودن lsof

### ISSUE THREAD

**Issue by radkesvat** [Ptechgithub/ReverseTlsTunnel#18]
سلام ؛ 
خیلی ممنون بابت اسکریپت زحمت کشیدین🙏🏻

لطفا چک کنید برنامه 
> lsof 

هم روی سیستم نصب باشه برای مالتی پورت لازمه ؛ روی ۹۹ درصد سیستم ها نصب هست ولی یکی اومده بود و مشکل داشت و فهمیدیم روی سیستم اش نصب نیست لذا چک و نصب بشه خیلی خوبه

**Comment by Ptechgithub** [comment]
سلام ، خواهش میکنم ممنون از شما. 
بله lsof اضافه شد
