### ISSUE TITLE
این خطا دلیلش چیه؟

### ISSUE THREAD

**Issue by abedin70** [Ptechgithub/ReverseTlsTunnel#19]
Cannot write to ‘install.sh’ (Success).
Which server do you want to use? (Enter '1' for Iran or '2' for Kharej) : 1
Please Enter SNI (default : splus.ir):
Please Enter Password (Please choose the same password on both servers): 123456
cat: write error: No space left on device
_### **Failed to start tunnel.service: Unit tunnel.service is masked.
Failed to enable unit: Unit file /etc/systemd/system/tunnel.service is masked.**_

**Comment by Ptechgithub** [comment]
با دسترسی root اجرا کنید.
ببینید فضای دیسک خالی داره؟
Uninstall کنید .
نشد سرور رو ریست کن
