### ISSUE TITLE
اپدیت برنامه

### ISSUE THREAD

**Issue by sakhb5** [Ptechgithub/ReverseTlsTunnel#2]
سلام اقا برنامه اقای راد اپدیت داده 
نسخه شما کی بروز میشه؟

**Comment by Ptechgithub** [comment]
سلام فقط یک بار uninstall کنید و مجدد install . اپدیت میشه

**Comment by ramtiny** [comment]
هر دو سرور ایران و خارج رو باید آپدیت کرد ؟
یا فقط سرور ایران؟

**Comment by Ptechgithub** [comment]
هردو

**Comment by ramtiny** [comment]
اون مکث و گیر چند ثانیه ای  آیا حل شده است؟
