### ISSUE TITLE
رو همراه اول جواب نمیده؟؟

### ISSUE THREAD

**Issue by abedin70** [Ptechgithub/ReverseTlsTunnel#20]
ادرس ای پی خارج تمیزه حتی بصورت مستقیم با همراه جواب میده
ولی با تانل وصل نمیشه!!
بنظرتون دلیلش چیه؟

**Comment by Ptechgithub** [comment]
سرور ایران چی اونم تمیزه؟

**Comment by abedin70** [comment]
> سرور ایران چی اونم تمیزه؟

بله
تو چک هاست اوکی هست

**Comment by abedin70** [comment]
> چک هاست روی همراه اول که تست نمیکنه. اگه کلا تانل کار نمی‌کنه نصبت اشکال داره اگه روی یک اپراتور خاص جواب نمیده سرورت رو باید عوض کنی

سپاس
