### ISSUE TITLE
Closed a exhausted mux connection

### ISSUE THREAD

**Issue by AkramiPro** [Ptechgithub/ReverseTlsTunnel#21]
درود این تانل خیلی خوب داره جواب میده واقعا ممنون از شما
فقط یه مشکلی که دارم یه سری هشدار هست داخل کنسول من نمیدونم چیه 
سرور من خیلی منابع بالایی داره میشه یک روش بگید گه کلا از تمام منابع استفاده کنه و محدودیت نداشته باشه ؟ 
خطای زیر رو الان میده :
Closed a exhausted mux connection

**Comment by Ptechgithub** [comment]
سلام از mux استفاده کردی؟

**Comment by AkramiPro** [comment]
من نسخه 4.1 هستم که طبق توضیحات دیدم نوشته پیشفرض mux روی 2 هست و منم تغییری ندادم

**Comment by Ptechgithub** [comment]
ظاهرا روی بعضی دیتا سنترها مشکل داره . مقدار رو زیاد کن اگه دیدی خطا داد ازش استفاده نکن

**Comment by ramtiny** [comment]
ببخشید mux چیه

**Comment by Ptechgithub** [comment]
https://github.com/radkesvat/ReverseTlsTunnel/blob/master/Mux.md

از این لینک توضیحات mux  رو میتونید بخونید
