### ISSUE TITLE
قطع شدن ارتباط بعد از چند دقیقه

### ISSUE THREAD

**Issue by sakhb5** [Ptechgithub/ReverseTlsTunnel#22]
سلام توی ورژن ۴/۵ 
بهد از چند دقیقه ارتباط با سرور خارج قطع میشه چجوری میشه ورژن قبل رو نصب کرد؟

**Comment by Ptechgithub** [comment]
https://github.com/radkesvat/ReverseTlsTunnel/tree/master


از صفحه اموزش نصب رو ببیند

**Comment by sakhb5** [comment]
با تغییر sni مشکل بر طرف شد
روی همین ورژن مرسی
