### ISSUE TITLE
انتخاب ورژن هنگام نصب

### ISSUE THREAD

**Issue by radkesvat** [Ptechgithub/ReverseTlsTunnel#23]
اقا ممنون اومدم بگم این قابلیتو اضافه کنین انگار اضافه شده دمتون گرم ؛ امیدوارم زود تر از دست باگ های باقی مونده راحت بشیم یه نسخه استیبل داشته باشیم به عنوان نسخه آخر ؛ فعلا که به 4.9 امیدوارم ببینیم چی بشه😅

**Comment by Ptechgithub** [comment]
واقعا خسته نباشید میگم.  کار سختیه امیدوارم که به جاهای بهتری برسه. 💚
