### ISSUE TITLE
استارت شدن

### ISSUE THREAD

**Issue by radkesvat** [Ptechgithub/ReverseTlsTunnel#24]
سلام وقت بخیر 

پیشناهاد میکنم بعد نصب یا حتی اپدیت خودش سرویس تانل رواستارت بکنه

و مشکلی هم پیش نمیاد که چند دقیقه بعد طول بکشه طرف سرور خارجشو استارت کنه و اگرم این ۲ تا گزینه استاپ و استوپ توی منو قرار بگیره و وضعیت ران بودن تونل هم نشون بده واقعا  عالی میشه. 

همچنین ممنون از زحمات و نسخه پنج خداروشکر مشکلی دیگه نداره طبق برسی ها و استیبل هست تونل از این نسخه.

**Comment by Ptechgithub** [comment]
سلام وقت شمام بخیر.

تا جایی که متوجه شدم چیزهایی که خواستید اضافه شد .لطفا چک کنید ببینید درسته

**Comment by radkesvat** [comment]
الان چک میکنم

**Comment by radkesvat** [comment]
تست کردم و اوکیه استارت میشن ؛  و دکمه استوپ و استارت شدن و چک استاتوس هم درست کار میکنه ✔

**Comment by Ptechgithub** [comment]
مرسی💚
