### ISSUE TITLE
فعال کردن mux

### ISSUE THREAD

**Issue by radkesvat** [Ptechgithub/ReverseTlsTunnel#25]
سلام 

وقتی که کاربر ماکس رو فعال میکنه و مثلا میزاره ۴

توی دستوری که توی سرویس نوشته میشه این مشکل پیش میاد
```sh
[Unit]
Description=Reverse TLS Tunnel


[Service]
Type=idle
User=root
WorkingDirectory=/root
ExecStart=/root/RTT --iran --lport:443 --other--   --mux:4--terminate:24
Restart=always

[Install]
WantedBy=multi-user.target
```

بین عدد ماکس و سوییچ terminate
باید یه اسپیس باشه که مشکل حل شه

**Comment by Ptechgithub** [comment]
سلام ممنون اصلاح شد

**Comment by Ptechgithub** [comment]
سلام. ممنون.
اصلاح شد

**Comment by Ptechgithub** [comment]
root@ubuntu-2gb-nbg1-5:~# ./RTT --iran --lport:23-65535 --sni:splus.ir --password:123p --accept-udp
version="5.1"
mode="iran"
listen_port=0
final_target_domain="splus.ir"
password="123p"
accept_udp=true
host=Hostent(name: "splus.ir", aliases: @[], addrtype: "AF_INET", length: 4, addrList: @["185.60.137.26"])
password="123p" password_hash="243A080041A1F9467E694945C56EA3E278A9E947" sh1=1307130027 sh2=1190561463 sh3=3655298136 pool_size=24
fs.file-max = 1000000
Firewall stopped and disabled on system startup
Mode Iran (Tcp + Udp): 91.107.251.1  handshake: splus.ir
reseting iptable nat
fatal.nim(53)            sysFatal
asyncfutures2.nim(426)   futureContinue
asyncfutures2.nim(426)   futureContinue
Error: unhandled exception: globals.nim(112, 9) `0 ==
    execCmdEx(&"""iptables -t nat -A PREROUTING -p {FWProtocol} --dport {multi_port_min}:{multi_port_max} -j REDIRECT --to-port {listen_port}""").exitCode`  [AssertionDefect]
reseting iptable nat
root@ubuntu-2gb-nbg1-5:~#



این خطای چیه؟

**Comment by radkesvat** [comment]
این برای فعال سازی مالتی پورته ؛ در حالت tcp و udp کامند عوض میشه ؛‌البته چون مالتی پورتو با یو دی پی هنوز تست نکرده بودم متوجه این باگ نشدم ؛ امشب اینا رو حل میکنم ممنون که گفتین ❤
