### ISSUE TITLE
درخواست

### ISSUE THREAD

**Issue by MoeinNS** [Ptechgithub/ReverseTlsTunnel#30]
امکانش هست اپشن parallel-cons:8 و connection-age:60 رو به قسمت نصب با سرویس اضافه کنین 
و اینکه یه توضیح کوچیک بدین که کاربرد اینا چیه

**Comment by radkesvat** [comment]
سلام ؛ اپشن parallel-cons فقط در سرور خارج نیاز به تنظیم هست و اجباری هم نیست ؛ دیفالتش ۸ هست

قابلیت ماکس دیگه اتومات حساب میشه پس لطفا سوال نشه از کاربر 

connection-age 

اجباری نیست ؛‌دیفالتش ۳۰ هست و اگه توسط کاربر تنظیم شد ؛ هم در سرور داخل و هم خارج باید تنظیم بشه و یکسان ست بشه

با تشکر از زحمات شما ❤

**Comment by Ptechgithub** [comment]
قابلیت mux حذف شد . برای اضافه کردن هر اپشن جدیدی میتونید از حالت custom استفاده کنید.
