### ISSUE TITLE
Load Balance

### ISSUE THREAD

**Issue by masih1998** [Ptechgithub/ReverseTlsTunnel#31]
سلام وقت شما بخیر
در بخش لود بالانس اسکریپت شما یک مشکلی وجود داره اونم اینه که وقتی میخوایم لود بالانس رو نصب کنیم از ما یک آیپی میگیره و روی همون یک سرور فقط لود بالانس میشه
منظورم اینه که ما اگر یک سرور خارج داشته باشیم و ۳ سرور ایران، سرور اول ایرانمون از طریق مالتی تانل، تانل میشه، سرور دوممون هم از طریق لود بالانس ولی دیگه نمیتونیم سرور سوم رو اضافه کنیم
به طور مثال میخوایم سرور سوم رو از طریق لود بالانس نصب کنیم اسکریپت به ما میگه قبلا لود بالانس نصب شده و اجازه اجرای لود بالانس روی سرور سوم ایرانمون رو بهمون نمیده

باتشکر از اسکریپت کارآمد شما دوست گلم💚

**Comment by Ptechgithub** [comment]
سلام دوست عزیز . حالت لود بالانس برای اتصال یک سرور ایران به چند سرور خارج نوشته شده. وقتی روی سرور ایران اجرا بشه ای پی سرور های خارج رو وارد میکنید و وقتی روی سرور خارج نصب میکنی اگر سرور v2ray بود فقط ای پی ایران و اگر سرور دوم خارجی بود ای پی سرور ایران و ای پی سرور v2ray رو وارد میکنید

**Comment by masih1998** [comment]
سلام مجدد عرض ادب
نه داداش گلم ببخشید تنها این صورت نیست که فقط لود بالانس برای یک سرور ایران به چند سرور خارج باشه
شما بی زحمت بخش راهنمای Load Balance اسکریپت رو مطالعه کنین👇

https://github.com/radkesvat/ReverseTlsTunnel/blob/master/docs/Loadbalancer.md

در اینجا مهندس خودش توضیح داده برعکس هم قابل انجامه
یعنی برای یک سرور خارج و چند سرور ایران هم قابل انجام هستش

اگر ممکنه این مورد هم به اسکریپتتون اضافه کنین که بتونیم از اسکریپتتون استفاده کنیم

بی نهایت از زحمات شما داداش گلم سپاسگذارم💚

**Comment by Ptechgithub** [comment]
بله میدونم. خود اسکریپت این حالت رو داره فقط. میتونید اجرا کنید ولی برعکس جواب بدید بعنی وقتی میپرسه سرور ایرانه بزن خارج و برعکس. یا حالت بهتر و راحت تر احرا به صورت custom هست دستورو بهش میدی خودش سرویسش رو میسازه

**Comment by masih1998** [comment]
به صورت custom بهتر هستش بنظرم
چون حالت برعکس نمیتونیم از قابلیت fake upload استفاده کنیم
ممنونم از شما

**Comment by masih1998** [comment]
فقط یک سئوال به صورت custom بی نهایت میتونیم تانل اجرا کنیم؟ مثلا تعداد سرور ها مهم نیست؟

**Comment by Ptechgithub** [comment]
بله میتونید روی هرچند تا که خواستید اجدا کنید
