### ISSUE TITLE
ارور در سرور ایران

### ISSUE THREAD

**Issue by fk6989** [Ptechgithub/ReverseTlsTunnel#32]
سلام
من تمام مراحل رو درست انجام دادم اما توی سرور ایران بعد از نصب مینویسه not running و وقتی گزینه ۳ رو میزنم که استارت شه مینویسه Tunnel service failed to start.

روی ۲ سرور ایران تست کردم. یکیش سیمین و یکیش شهریار هر دو از آروان.

روی سرور خارج مشکلی نداره و مینویسه running

**Comment by Ptechgithub** [comment]
سلام احتمالا مشکل از نصب یا سرورتون باشه

**Comment by Ptechgithub** [comment]
با یوزر root اجرا کنید.
اگر سرور غیر اروان دارید روی اونم تست کنید ببینید چه جوریه.

**Comment by masih1998** [comment]
سلام دوست گلم
مشکل از دیتاسنتر نیست
این ارور ممکنه رو من روی سرور خارج هم دیدم
اگر روی سرور خارج یا ایران به ارور not running برخورد کردی
دستور

> apt --fix-broken install -y

رو بزنی بعدش تانل کنی، تانل به حالت اجرا در میاد

**Comment by Ptechgithub** [comment]
سلام این دستور برای وقتیه که یه پکیج روی سرور حین نصب یا لغو نصب دچار مشکل شده باشه . مثل زمانی که دستور apt upgrade رو میزنی ولی چون سرعتش کنده یا لغو میکنی یا خودش لغو بشه. دوباره که بخوای upgrade کنی خطا میده

**Comment by masih1998** [comment]
من وقتی تانل رو اجرا میکنم و not running میشه 
این دستور رو میزنم اوکی میشه
حتی خود لینوکس همینو اون زمان اطلاع میده

**Comment by Ptechgithub** [comment]
https://github.com/radkesvat/ReverseTlsTunnel/issues

تو این صفحه مشکل رو عنوان کنید
