### ISSUE TITLE
تانل به چند خارج

### ISSUE THREAD

**Issue by MAhdioypu** [Ptechgithub/ReverseTlsTunnel#33]
سلام وقتتون بخیر 
اگه خواسته باشه یک ایران به 2 خارج تانل کنیم باید از چه روشی استفاده کنیم ؟

**Comment by Ptechgithub** [comment]
سلام از Loadbalancer استفاده  کنید

**Comment by MAhdioypu** [comment]
سرور اولی کار میکنه تو این روش اما سرور دومی کار نمیکنه
