### ISSUE TITLE
کندی سرعت در تانل

### ISSUE THREAD

**Issue by MahdiMadhani** [Ptechgithub/ReverseTlsTunnel#35]
با سلام
15 روزی هستش من با اسکریپت زیر برای ایجاد تانل استفاده کردم
bash <(curl -fsSL https://raw.githubusercontent.com/radkesvat/ReverseTlsTunnel/master/scripts/RtTunnel.sh)
https://youtube.com/watch?v=1mj1fhA2X6s این هم دیدم
همچی اوکی بود ولی چند روزی هست سرعتش بالا و پایین میشه
 به نظرتون چه کار کنیم
با تشکر

**Comment by Ptechgithub** [comment]
سلام sni رو عوض کن.

**Comment by MahdiMadhani** [comment]
> سلام sni رو عوض کن.

کانفیگ ها دادم دست مشتری دسترسی هم به مشتری ندارم

**Comment by Ptechgithub** [comment]
تعداد کلاینتها و مصرف cpu زیاد نباشه . روی سرور دیگه تست کن

**Comment by MahdiMadhani** [comment]
> ظاهرا مشکل از سرور خارجه که اتصال ضعیف شده باید از یه سایت دیگه سرور بگیرید تست کنید. طبق گفته سازنده ی rtt

دو روزه دارم با دستور speedtest هم همزمان دوتا سرود رو تست میکنم
سرعت دانلود و اپلود سرور خارج زیر 60 مگ نمیاد و اوکیه
سرعت دانلود سرور ایران هم اوکیه.ولی وقتی سرعت اپلود سرور ایران زیر 15مگ میشه کندی سرعت پیش میاد.
ما از صبح تا ساعت 21 تست رو انجام دادیم وسرعت اوکی بود و سرعت اپلود ایران بالای 30مگ بود 
ولی ساعت 21 به بعد سرعت اپلود   زیر 14 مگ میاد و کندی سرعت داشتیم.
ما به این نتیجه رسیدیم مشکل از پایین بودن اپلود سرور ایران هستش.
لطفا بفرمایید نتیجه ما درست هست یا خیر.
باتسکر

**Comment by Ptechgithub** [comment]
اینکه سرعت در  یه ساعت هایی افت کنه طبیعیه ولی اینکه قطع و وصل بشه فک نکنم ربطی به سرعت اپلود داشته باشه. یعنی من ندیدم همچین موردی.
