### ISSUE TITLE
آپلود فیک

### ISSUE THREAD

**Issue by MahdiMadhani** [Ptechgithub/ReverseTlsTunnel#36]
با سلام
میخواهیم ی سرور ایران تهیه کنیم گفتن در صورتی که مصرف 1 به 10 باشه اوکیه.
ایا اپلود فیک رو فعال کنیم مصرف 1 به 10 رعایت میشه؟
با تشکر

**Comment by hadim998** [comment]
سلام آپلود فیک روی udp هست یا tcp
?
