### ISSUE TITLE
اگر ممكن هست mux دوباره فعال بفرماييد

### ISSUE THREAD

**Issue by hatinati2** [Ptechgithub/ReverseTlsTunnel#37]
سلام وقت بخير
اگر ممكن هست mux دوباره فعال بفرماييد
يا مثل آپلود فیک که سوال می پرسه برای فعال سازیش اون مدلی باشه
چون واقعا کیفیت اتصال خیلی خیلی بهتر می کنه

با تشکر از زحمات شما

**Comment by Ptechgithub** [comment]
سلام
از نسخه ۶ به بالا ماکس اتومات فعاله و محاسبه میشه.

**Comment by hatinati2** [comment]
مرسی متشکرم
