### ISSUE TITLE
UDP

### ISSUE THREAD

**Issue by xQuantoM** [Ptechgithub/ReverseTlsTunnel#38]
سلام چطوری udp میتونم فعال کنم؟

**Comment by Ptechgithub** [comment]
https://github.com/radkesvat/ReverseTlsTunnel/blob/master/docs/Udp.md

سلام این لینک رو مطالعه بفرمایید

**Comment by xQuantoM** [comment]
دیدم الان زدم --accept-udp کامند نات فاند میده

**Comment by Ptechgithub** [comment]
توی همون صفحه issue باز کنید
