### ISSUE TITLE
مشکل استارت شدن سرویس در سرور داخلی

### ISSUE THREAD

**Issue by Saleh-Mumtaz** [Ptechgithub/ReverseTlsTunnel#39]
درود ،  
در سروری از کاریکاتور داخلی کلاودفلر، وقتی اسکریپت رو اجرا میکنم خطای زیر رو میده:

![image](https://github.com/Ptechgithub/ReverseTlsTunnel/assets/83896125/4b481964-31ef-4dda-a562-ba0cecd2bbb3)
![image](https://github.com/Ptechgithub/ReverseTlsTunnel/assets/83896125/ba11ebcf-4ca3-4a5c-845c-9211e5be7498)

**Comment by Ptechgithub** [comment]
سلام ببینید پورت تکراری استفاده نشده . بهتره سرور رو rebuild کنی.

**Comment by Saleh-Mumtaz** [comment]
درود، سرور جدیدی درست کردم، بازهم سرویس استارت نمی‌شود. تا الان بامداد را امتحان میکردم روی بقیه هم تست میکنم و اطلاع میدم. اگر لاگی نیاز هست برای بررسی بیشتر در اختیارتون بگذارم اطلاع بدید.

**Comment by diedie65** [comment]
بندهم همین مشکل رو دارم .

**Comment by Saleh-Mumtaz** [comment]
بنده به صورت دستی در نهایت ریورس تانل رو اجرا کردم، اینجا ایشیو باز کردم به جهت بررسی و کمک به حل مشکل برای کسانی که با اسکریپت میخوان اجرا کنن.

**Comment by Ptechgithub** [comment]
![1](https://github.com/Ptechgithub/ReverseTlsTunnel/assets/118217228/b2b582db-705d-41b4-8ceb-261eeb5ea128)

تست گرفتم مشکلی نداره سرور رو عوض کنید

**Comment by Saleh-Mumtaz** [comment]
بسیار عالی، روی کدام دیتاسنتر تست گرفتید؟ این مشکل روی بامداد هست، دوتا سرور هم روش تست گرفتم

**Comment by Ptechgithub** [comment]
بامداد کلا برای من login هم نکرد روی فروغ تست گرفتم

**Comment by Saleh-Mumtaz** [comment]
بنظر شما بهترین دیتاسنترشون کدوم هست؟ من فکر میکردم بامداد باشه...

**Comment by Saleh-Mumtaz** [comment]
روی بامداد با رمز عادی سرورا کار نمیدن فقط کلید ssh کار میده، چندین بار امتحان کردم

**Comment by Ptechgithub** [comment]
نمیدونم خودم اصلا استفاده نمیکنم از سرور ایرانی

**Comment by ramtiny** [comment]
سلام چرا تانل ریورس با اسکریپت شما
روی دیتاسنتر آسیاتک جواب نمیده؟
ولی روی همین دیتاسنتر با روش آیپیتیل جواب میده؟

**Comment by Ptechgithub** [comment]
سلام چون روششون کامل فرق میکنه

**Comment by mohsn-mirzaei** [comment]
> بنده به صورت دستی در نهایت ریورس تانل رو اجرا کردم، اینجا ایشیو باز کردم به جهت بررسی و کمک به حل مشکل برای کسانی که با اسکریپت میخوان اجرا کنن.

سلام، اگر میشه جزئیات دستی ریورس تانل کردنو توضیح بدید، من هم با اسکریپت نتونستم اجرا کنم!

**Comment by Saleh-Mumtaz** [comment]
> > بنده به صورت دستی در نهایت ریورس تانل رو اجرا کردم، اینجا ایشیو باز کردم به جهت بررسی و کمک به حل مشکل برای کسانی که با اسکریپت میخوان اجرا کنن.
> 
> سلام، اگر میشه جزئیات دستی ریورس تانل کردنو توضیح بدید، من هم با اسکریپت نتونستم اجرا کنم!

درود، اموزش اجرا به صورت سرویس رو بخونید من از همون استفاده کردم.

**Comment by mohsn-mirzaei** [comment]
> > > بنده به صورت دستی در نهایت ریورس تانل رو اجرا کردم، اینجا ایشیو باز کردم به جهت بررسی و کمک به حل مشکل برای کسانی که با اسکریپت میخوان اجرا کنن.
> > 
> > 
> > سلام، اگر میشه جزئیات دستی ریورس تانل کردنو توضیح بدید، من هم با اسکریپت نتونستم اجرا کنم!
> 
> درود، اموزش اجرا به صورت سرویس رو بخونید من از همون استفاده کردم.

سرور رو ری‌بیلد کردم با اسکریپت جواب داد! ممنون
