### ISSUE TITLE
مشکل نصب روی سرور ایران

### ISSUE THREAD

**Issue by shehnipoor** [Ptechgithub/ReverseTlsTunnel#40]
سلام من هرچند باری ک روی سرور ایران میزنم بدون خطا تا اخرین مرحله میره
اما وضعیت سرور اینه:
Multiport is:    [Not running ✗ ]
Load balancer is:[Not running ✗ ]
Custom Tunnel is:[Not running ✗ ]

**Comment by shehnipoor** [comment]
جالب اینه ک دوبارم سیستم عاملو عوض کردم و روی ابونتو 20 و 22 تست کردم

**Comment by Ptechgithub** [comment]
سلام . سرورت مال کجاست

**Comment by imanerfanian** [comment]
سلام منم همین مشکل رو دارم. سرور آسیاتک هست

**Comment by shehnipoor** [comment]
> سلام منم همین مشکل رو دارم. سرور آسیاتک هست

> سلام منم همین مشکل رو دارم. سرور آسیاتک هست


روی ابونتو نتونستم کاری از پیش ببرم
اما یه راهی میگم که بهت جواب می‌ده (تست شده)

ابتدا بازسازی سرور را بزنید و دبیان نسخه ۱۱ را روی سرور‌تان نصب کنید.

سپس به سرور ssh بزنید و دستور زیر را بزنید که بتونید dnsها را ویرایش کنید.

nano /etc/resolv.conf

وقتی فایل dnsها را باز کردید، ۲ تا dns وجود داره

اولین را به 8.8.8.8 تغییر بدید و دومین را هم به 8.8.4.4 تغییر بدید و ctrl+x را بزنید و سپس y را بزنید تا dnsها ویرایش شوند.

سپس دستور apt-get update را بزنید تا سرور آپدیت بشه (البته آخر اپدیت یک خطا می‌ده که مهم نیست).

سپس دستور apt-get install curl -y را بزنید تا curl روی سرورتان نصب شود.

حالا فایل نصبی ReverseTlsTunnel را اجرا کنید و نصبش کنید، بدون مشکل نصب می‌شه.

موفق باشید. 🥰

**Comment by imanerfanian** [comment]
اوبونتو خودش Debian-Base هست پس نباید تفاوتی در ساختار اصلی سیستم عامل بین این دوتا داشته باشه که من برم اونو نصب کنم.
همچنین اگر قراره تو نصب اسکریپت چیزیو curl کنه همونجا باید خطا بده تا بررسی کنیم اما اسکریپت روی Multiport داره کامل نصب میشه بدون خطا و بعدش به مشکل میخوره و لاگی هم ثبت نمیکنه پس یکم توضیحاتی که دادید عجیب بود برام!
