### ISSUE TITLE
اختلال در اتصال 

### ISSUE THREAD

**Issue by pjalil74** [Ptechgithub/ReverseTlsTunnel#43]
بعد از بررسی زیاد از دیتا سنتر های متفاوت بیش 5 تا دیاتاسنتر این نسخه باعث افزایش پینگ هست و قطعی و وصلی هست بعد از چند ساعت ولی نسخه های قدیمی این مشکل نداره

**Comment by Ptechgithub** [comment]
مرسی فعلا از نسخه های قبلی استفاده کنید تا ببینیم اپدیت میشه

**Comment by darklies** [comment]
نسخه قدیمی رو از کجا پیدا کنیم ؟

**Comment by Ptechgithub** [comment]
وقتی میپرسه یه آخرین نسخه رو میخوای نصب کنی no رو بزن بعد اون ورژنی که میخوای نصب کنی رو وارد کن
