### ISSUE TITLE
آپلود 1 به 1

### ISSUE THREAD

**Issue by mahdiush** [Ptechgithub/ReverseTlsTunnel#44]
من توی چند تا دیتا سنتر و سرور های مختلف در ایران تست کردم و دیدم که زمانی که آپلود فیک رو غیر فعال میکنید باز هم آپلود فیک داره !!!
و به هر میزان که دانلود مصرف میکنید به همون میزان آپلود محاسبه میشه !!
چیکار باید کرد ؟

**Comment by Ptechgithub** [comment]
وقتی به هر میزان دانلود کنی ب همون میزان هم اپلود داری یعنی اپلود فیکی انجام نشده و حالت عادی یک به یک داره حساب میشه
