### ISSUE TITLE
نصب نسخه ۵.۴

### ISSUE THREAD

**Issue by MahdiMadhani** [Ptechgithub/ReverseTlsTunnel#46]
با سلام
  چطور میتونیم نسخه ۵ رو نصب کنیم

**Comment by Ptechgithub** [comment]
سلام اونجا که میپرسه ورژن اخر رو میخوای نصب کنی به جای تایید ورژن مورد نظر رو وارد کن

**Comment by MahdiMadhani** [comment]
انجام دادم بعد از نیم ساعت ارتباط قطع میشه

**Comment by Ptechgithub** [comment]
اونو باید ورژن جدید بزنه تا مشکلی اگه داره رفع بشه
