### ISSUE TITLE
اتصال بدون پنل

### ISSUE THREAD

**Issue by fery379** [Ptechgithub/ReverseTlsTunnel#5]
بدون نصب پنل سناعی هم میشه از این اسکریپت استفاده کرد؟
توی ویتوری مقادیر رو چطور قرار بدیم؟

**Comment by Ptechgithub** [comment]
بله میشه .
فقط ای پی ایران رو به جای ای پی خارج بزارید

**Comment by fery379** [comment]
پس چرا همش ارور connection closed و connection refused میده

**Comment by Ptechgithub** [comment]
https://github.com/radkesvat/ReverseTlsTunnel/tree/master

مشکل رو از صفحه ی ایشون پیگیر بشید.
