### ISSUE TITLE
سوال در مورد ip

### ISSUE THREAD

**Issue by Cjxer** [Ptechgithub/ReverseTlsTunnel#6]
سلام وقتتون بخیر 🌹
خیلی ممنون بابت این اسکریپت عالی 👌🏻

فقط یه سوالی داشتم
من میخواستم از ip limit برای کاربرانی که تانل شدن استفاده کنم
میخواستم بدونم که آیا این اسکریپت ، وقتی دیتارو از سرور ایران به خارج و یا برعکس انتقال میده
توی سرور خارج که xui و یا مرزبان نصب شده ، آیا ip فردی که متصل شده لاگ میشه یا ip سرور ایران ؟

یعنی کلا ip فرد متصل ارسال میشه به سرور خارج یا خیر؟

ممنون از شما 🙏🏻

**Comment by Ptechgithub** [comment]
سلام ip limit تو حالت عادی هم که تست کردم جواب نمیده. برای این تانل هم تست نکردم متأسفانه.  میتونید تست کنید
