### ISSUE TITLE
نصب مجدد

### ISSUE THREAD

**Issue by MILADALEF** [Ptechgithub/ReverseTlsTunnel#8]
سلام . آیا هربار که از طریق این اسکریپت uninstall و اینستال مجدد میکنیم نسخه جدید برنامه اصلی نصب میشود ؟؟ چون الان ورژن دو آمده و من زمان ورژن ۱.۲ با اسکریپت شما نصب کردم

**Comment by Ptechgithub** [comment]
سلام بله اپدیت میشه
