### ISSUE TITLE
آپدیت میشه ؟

### ISSUE THREAD

**Issue by teststar121** [Ptechgithub/ReverseTlsTunnel#9]
سلام عزیز خسته نباشید دمت گرم
آقا این بش اسکریپت آپدیت میشه به نسخه های جدید گیت هاب radkesvat ؟! یا یه نسخه ی قدیمی باقی میمونه ؟

**Comment by Ptechgithub** [comment]
بله اسکریپت رو مجدد اجرا کنید

**Comment by teststar121** [comment]
منظورم اینه خودش به نسخه ی آخر پروژه ی اصلی آپدیت میشه ؟ یا شما خودت باید آپدیت کنی  ؟
چون شاید شما دیگه حواست به این نباشه

**Comment by Ptechgithub** [comment]
اپدیت کردم. اگه فقط نسخه تغییر کنه خودش اپدیت میشه. شما فقط لازمه یک بار دیگه نصب رو انجام بدید
